package vcnc.tpile.trash;

/*

The types of statements generated by Layer00, which removes M98, M99 and
O-codes.

*/


public class St00 extends St01 {

  // The next layer removes...
  public static final short G20   = 3000;   // Inches
  public static final short G21   = 3001;   // Millimeters.
  
  
  public St00(short type) {
    super(type);
  }
  

  public String toString() {

    if (this.type == G20)
      return(String.format("N%05d\tG20",lineNumber));
    if (this.type == G21)
      return(String.format("N%05d\tG20",lineNumber));
    
    return super.toString();
  }
}
