package vcnc.tpile.trash;

/*

The types of statements generated by Layer0B, which removes wizards.

*/

import vcnc.tpile.parse.DataSubProg;
import vcnc.tpile.parse.DataSubroutineCall;


public class St0B extends St00 {
  
  // Emitted by Layer0B, but not emitted thereafter:
  public static final short PROG  = 2000;  // An O-code, like O1234
  public static final short M98   = 2001;  // Call subprogram
  public static final short M99   = 2002;  // Return from subprogram


  public St0B(short type) {
    super(type);
  }
  

  public String toString() {
    
    if (this.type == PROG)
      {
        DataSubProg ovalue = (DataSubProg) data;
        return String.format("N%05d\tO%05d",lineNumber,ovalue.progNumber);
      }
    
    if (this.type == M99)
      return(String.format("N%05d\tM99",lineNumber));
    
    if (this.type == M98)
      {
        DataSubroutineCall call = (DataSubroutineCall) data;
        
        String answer = String.format("N%05d\tM98 ",lineNumber);
        answer += String.format("P%05d ",call.programNumber);
        if (call.invocations > 1)
          answer += String.format("L%04d",call.invocations);
        return answer;
      } 
    
    // Must be a type known to a super-class.
    return super.toString();
  }
  
}
