package vcnc.tpile.parse;

// Holds a buffer of Statement objects, as generated by the Parser.

public class StatementBuffer {

	// The number of statements in each buffer.
  // BUG: I'm not so sure this should be static (or public). It may be
  // better to go with a different data structure -- more dynamic.
  // Also, this may need to have three buckets (not two) due to cutter comp.
	public static int BufferSize = 20;
	
	public Statement[] first = null;
	public Statement[] second = null;
	
	// The next Statement in this.first to be consumed.
	public int index = 0;
}
