package vcnc.tpile.parse;

// Holds a buffer of Statement objects, as generated by the Parser.

public class StatementBuffer {

	// The number of statements in each buffer. 
	public static int BufferSize = 20;
	
	public Statement[] first = null;
	public Statement[] second = null;
	
	// The next Statement in this.first to be consumed.
	public int index = 0;
}
